[GLOBAL]
# Versions I tried: 2.14.0, 2.17.0.dev4
pants_version = "2.17.0.dev4"

backend_packages = [
    "pants.backend.python",
]

[anonymous-telemetry]
enabled = "false"

[python]
interpreter_constraints = [">=3.8,<3.9"]
enable_resolves = true
default_resolve = "python-default"

[python.resolves]
python-default = "python.lock"
